#!/usr/bin/env python3
"""
Builds CODE_WALKTHROUGH.pdf -- a line-by-line annotated walkthrough of every
authored file in this project (scrape.py, generate_report.py, the two GitHub
Actions workflows, requirements.txt). Generated data files (jobs.json,
jobs.md, index.html, report_state.json, latest_report.pdf) are not authored
line-by-line and are only summarized.

Not run on a schedule -- this is documentation, regenerated by hand
whenever the annotated files change meaningfully:

    python generate_code_doc.py
"""
from pathlib import Path

from fpdf import FPDF
from fpdf.enums import XPos, YPos

REPO_DIR = Path(__file__).resolve().parent
OUT_PATH = REPO_DIR / "CODE_WALKTHROUGH.pdf"

CODE_FILL = (240, 242, 245)
EXPLAIN_COLOR = (70, 78, 92)
HEADING_COLOR = (20, 23, 28)


_ASCII_SUBSTITUTIONS = {
    "—": "--",  # em dash
    "–": "-",   # en dash
    "‘": "'",
    "’": "'",
    "“": '"',
    "”": '"',
}


def safe(text: str) -> str:
    """Core PDF fonts (Helvetica/Courier) only support latin-1 -- swap common
    unicode punctuation for its ASCII equivalent first, so code containing it
    (e.g. scrape.py's em dash) renders as the intended character rather than
    a literal '?'."""
    text = text or ""
    for uni, ascii_equiv in _ASCII_SUBSTITUTIONS.items():
        text = text.replace(uni, ascii_equiv)
    return text.encode("latin-1", "replace").decode("latin-1")


# Each file's annotations are a list of (first_line, last_line, explanation)
# tuples, in order, covering every line of the file with no gaps. The code
# text itself is read live from disk -- only the explanations are authored.

SCRAPE_PY_ANNOTATIONS = [
    (1, 1, "Shebang, so the file can also be run directly as ./scrape.py on a Unix-like system."),
    (2, 9, "Module docstring: states the project's core constraint up front -- only LinkedIn's public, "
           "logged-out guest search is ever touched, no login or credentials, and points to the workflow "
           "file that schedules this script."),
    (10, 16, "Standard-library imports: json (read/write jobs.json), re (parsing job ids and relative "
             "\"posted\" text), sys (stderr for warnings), time (the inter-page delay), urllib.parse "
             "(building the query string), Path (filesystem paths), datetime/timezone (UTC timestamps)."),
    (17, 17, "Blank line separating standard-library imports from third-party imports."),
    (18, 20, "Third-party imports: BeautifulSoup parses the HTML LinkedIn returns; webdriver and "
             "ChromeOptions (from Selenium) drive a real headless Chrome browser instead of a raw HTTP "
             "request."),
    (21, 21, "Blank line before the path constants."),
    (22, 22, "REPO_DIR resolves to the directory this script itself lives in, so output paths are correct "
             "no matter what directory the script is invoked from (important under GitHub Actions)."),
    (23, 25, "The three output files this script maintains: the machine-readable JSON record, the "
             "human-readable markdown table, and the static HTML page GitHub Pages serves."),
    (26, 26, "Blank line before the search parameters."),
    (27, 28, "The exact search query sent to LinkedIn: keywords \"DSA Trainer\", location \"India\" -- the "
             "single place to change if the tracked search should change."),
    (29, 29, "GUEST_SEARCH_URL: LinkedIn's public jobs-guest search API -- the same endpoint LinkedIn "
             "serves to anonymous visitors and search-engine crawlers, requiring no session at all."),
    (30, 32, "Pagination and pacing constants: 10 results per page, up to 6 pages, with a 2-second pause "
             "between page loads so the scraper behaves politely rather than hammering the endpoint."),
    (33, 33, "Blank line before the user-agent string."),
    (34, 37, "USER_AGENT: an ordinary desktop Chrome string, so requests look like a normal browser visit "
             "rather than a bare script -- passed to Chrome itself via build_driver() below."),
    (38, 38, "Blank line before the freshness-window constants."),
    (39, 40, "MIN_AGE_DAYS / MAX_AGE_DAYS: a listing is only tracked once it is at least 1 day old, and is "
             "dropped again once it is older than about a month (31 days)."),
    (41, 41, "Blank line before the unit-conversion table."),
    (42, 49, "_UNIT_TO_DAYS: converts each unit LinkedIn's relative \"posted\" text can use (minute, hour, "
             "day, week, month, year) into a fraction of a day, so any of them can be turned into a single "
             "comparable number."),
    (50, 51, "Two blank lines -- PEP 8 spacing before the first function definition."),
    (52, 53, "parse_age_days: function signature and docstring -- turns LinkedIn's relative text into an "
             "approximate age in days, or None if it can't be parsed."),
    (54, 54, "Normalizes the input: falls back to an empty string if None was passed, strips whitespace, "
             "lowercases it so matching below is case-insensitive."),
    (55, 56, "An empty string can't be parsed -- return None immediately."),
    (57, 58, "LinkedIn's \"just now\" / \"a moment ago\" phrasing is treated as age zero."),
    (59, 60, "\"Yesterday\" is treated as exactly 1 day old (LinkedIn doesn't say \"1 day ago\" for this "
              "case)."),
    (61, 61, "The general case: a regex pulls out a number and a unit word from phrasing like \"3 days ago\" "
             "or \"2 weeks ago\" (the trailing \"s?\" makes the plural optional, so \"1 day ago\" also "
             "matches)."),
    (62, 63, "If the text didn't match that pattern at all (an LinkedIn phrasing this script doesn't "
             "recognize), give up and return None rather than guessing."),
    (64, 65, "Otherwise convert the matched count to an integer and multiply by that unit's day-fraction "
             "from _UNIT_TO_DAYS to get the final approximate age."),
    (66, 67, "Two blank lines before the next function."),
    (68, 70, "in_age_window: the single freshness check used everywhere else in the script -- parses the "
             "age and reports whether it falls between MIN_AGE_DAYS and MAX_AGE_DAYS inclusive."),
    (71, 72, "Two blank lines before the Selenium setup function."),
    (73, 79, "build_driver: configures and returns one headless Chrome instance -- \"--headless=new\" runs "
             "without a visible window, \"--no-sandbox\" and \"--disable-dev-shm-usage\" are the standard "
             "flags needed for Chrome to run inside a restricted CI container, and the custom user-agent "
             "keeps the browser looking like an ordinary desktop visit."),
    (80, 81, "Two blank lines before the page-fetch function."),
    (82, 86, "fetch_page(driver, start): builds the paginated search URL for a given page offset, points "
             "the already-open Selenium browser at it with driver.get(), and returns the fully rendered "
             "page's HTML -- this is the one function that changed when the project moved from a raw "
             "urllib request to a real browser."),
    (87, 88, "Two blank lines before the HTML-parsing function."),
    (89, 114, "parse_cards(html): parses one page of results with BeautifulSoup. Selects every "
              "\"div.base-card\" result card, and for each one pulls the title, company, location, "
              "relative posted-time, and the canonical job link; skips a card entirely if it's missing a "
              "title or a link (defensive against a malformed card); extracts the numeric job id from the "
              "trailing digits of the URL (falling back to the whole URL if that pattern doesn't match); "
              "and returns the list of listing dicts found on that page."),
    (115, 116, "Two blank lines before the orchestration function."),
    (117, 142, "fetch_all_listings(): the main scraping loop. Creates one Chrome driver for the whole run "
               "(not one per page), then for each page: fetches it, and stops early if the fetch itself "
               "raised an exception (logging a warning to stderr first), or if the page came back with no "
               "cards at all. Otherwise merges every listing into an all_listings dict keyed by job id "
               "(this is the de-duplication step -- a repeated id is simply overwritten with the same "
               "data). If an entire page added zero new ids, LinkedIn has started repeating results and "
               "the loop stops there rather than wasting further requests. A short sleep between pages "
               "keeps requests spaced out. The `finally` block guarantees driver.quit() runs even if "
               "something above raised, so a failed run never leaves an orphaned Chrome process behind. "
               "Returns the deduplicated listings as a plain list."),
    (143, 144, "Two blank lines before the state-loading function."),
    (145, 148, "load_existing(): reads the previously written jobs.json, or returns an empty list on the "
               "very first run when the file doesn't exist yet."),
    (149, 150, "Two blank lines before the output-writing function."),
    (151, 166, "write_outputs(jobs): sorts all tracked jobs newest-first by first_seen_utc, writes that "
               "exact structure to jobs.json as indented JSON, builds the equivalent markdown table and "
               "writes jobs.md, then calls build_index_html to regenerate the live HTML page from the same "
               "sorted list."),
    (167, 168, "Two blank lines before the HTML-building function."),
    (169, 219, "build_index_html(jobs_sorted): builds one HTML table row per job (every field passed "
               "through escape_html so a title or company containing \"&\", \"<\", \">\" or a quote can't "
               "break the page), then renders a complete static HTML document around those rows -- inline "
               "CSS with a `color-scheme: light dark` declaration so it adapts to the visitor's OS theme, a "
               "sticky table header, a horizontally-scrollable wrapper for narrow screens, a live count and "
               "generated-at timestamp in the page's meta line, and a link back to the source repo -- and "
               "writes the result to index.html."),
    (220, 221, "Two blank lines before the escaping helper."),
    (222, 229, "escape_html(text): a minimal, dependency-free HTML-escaping helper for the four characters "
               "that matter (&, <, >, \") -- used every time job data is interpolated into the generated "
               "page."),
    (230, 231, "Two blank lines before the entry-point function."),
    (232, 234, "main() begins: loads whatever was already being tracked from jobs.json into by_id, a dict "
               "keyed by job id, so new results can be merged in below."),
    (235, 236, "Runs the full scrape (fetch_all_listings) to get this run's live results, and captures the "
               "current time once as an ISO-8601 UTC string to stamp any newly-discovered listings with."),
    (237, 237, "Blank line."),
    (238, 241, "If the scrape returned nothing at all (for example Chrome/Selenium failed to start, or the "
               "network call failed), the run stops here without touching jobs.json -- this guards against "
               "a transient failure silently wiping out everything that was previously tracked."),
    (242, 243, "Blank line before the merge loop."),
    (244, 263, "For every listing just fetched: if its id isn't already tracked, it's only adopted once its "
               "posted-text falls inside the freshness window (skipping anything too fresh or already "
               "stale), then it's stamped with first_seen_utc and added to both by_id and the new_jobs "
               "list that will be reported in this run's log output. If the id was already tracked, its "
               "mutable fields (title, company, location, posted text, url) are refreshed in place from "
               "the live page, but its original first_seen_utc is deliberately left untouched so the "
               "tracker's history stays accurate."),
    (264, 268, "After merging, every tracked listing (old or new) is re-checked against the freshness "
               "window using its current posted-text, and anything that has aged out is dropped from the "
               "final list -- dropped is just the count of how many, for the log line below."),
    (269, 269, "Blank line."),
    (270, 270, "Persists the final, filtered list via write_outputs -- this is the one place jobs.json / "
               "jobs.md / index.html actually get written."),
    (271, 272, "Blank line before the summary output."),
    (273, 274, "Prints a machine-readable RESULT summary line (counts of new/total/dropped), then one NEW: "
               "line per freshly-added listing -- both become part of the GitHub Actions run log."),
    (275, 276, "Two blank lines before the module entry-point guard."),
    (277, 278, "Standard `if __name__ == \"__main__\": main()` guard, so main() only runs when the file is "
               "executed directly, not if it were ever imported."),
]

GENERATE_REPORT_PY_ANNOTATIONS = [
    (1, 1, "Shebang."),
    (2, 12, "Module docstring: states this script's purpose (build and email a PDF summary roughly every "
            "5 days) and lists the three GitHub Actions secrets it needs -- explicitly noting these are "
            "set by the repo owner and never seen or stored by Claude."),
    (13, 20, "Imports: json/os/smtplib/datetime/Path for data and email plumbing, the three email.mime "
             "classes needed to build a multipart message with a PDF attachment, and fpdf2's FPDF class "
             "plus its XPos/YPos enums (used to control the text cursor after each multi_cell call)."),
    (21, 21, "Blank line before the path/URL constants."),
    (22, 28, "REPO_DIR (this file's own directory), the three file paths this script reads or writes "
             "(jobs.json, report_state.json, latest_report.pdf), and the two URLs included in every "
             "report."),
    (29, 33, "Blank lines separating the constants block from the first function."),
    (34, 37, "load_jobs(): reads jobs.json, or returns an empty list if it hasn't been created yet."),
    (38, 39, "Blank lines."),
    (40, 43, "load_state(): reads report_state.json, or defaults to the Unix epoch as "
             "last_reported_utc -- so on the very first run, every currently-tracked job counts as "
             "\"new\"."),
    (44, 45, "Blank lines."),
    (46, 47, "save_state(state): writes the (updated) state dict back to report_state.json."),
    (48, 49, "Blank lines."),
    (50, 52, "pdf_safe(text): fpdf2's built-in Helvetica font only supports the latin-1 character set, so "
             "any job title/company containing an emoji, a curly quote, or non-Latin script is re-encoded "
             "to latin-1 with lossy replacement here, before it ever reaches the PDF -- without this, such "
             "a listing would crash the whole report."),
    (53, 54, "Blank lines."),
    (55, 59, "build_pdf() begins: creates a new FPDF document, turns on automatic page breaks with a 15mm "
             "bottom margin (so a long listings section flows onto new pages by itself), and adds the "
             "first page."),
    (60, 61, "Prints the report's bold 16pt title line."),
    (62, 68, "Prints five 10pt meta lines: when the report was generated, how many listings are tracked in "
             "total, how many are new since the last report, and the live page + repo URLs."),
    (69, 69, "A 6mm vertical gap before the listings section."),
    (70, 70, "Blank line."),
    (71, 72, "Decides what to actually list: the new listings if there are any, otherwise the full "
             "tracked set, with a heading string chosen to match."),
    (73, 75, "Prints that heading in bold 12pt, followed by a small 2mm gap."),
    (76, 76, "Blank line."),
    (77, 77, "Switches to plain 9pt body font for the per-listing loop below."),
    (78, 92, "The per-listing loop: pulls title/company/location/posted/url through pdf_safe(), prints the "
             "title in bold, then a single line combining company, location and posted-time, then the URL "
             "rendered in blue (RGB 0,0,200) with the text color reset back to black immediately after so "
             "it doesn't bleed into the next entry -- followed by a 3mm gap before the next listing."),
    (93, 93, "Blank line."),
    (94, 95, "Writes the finished document to PDF_PATH (latest_report.pdf) and returns that path to the "
             "caller."),
    (96, 97, "Blank lines before the emailing function."),
    (98, 101, "send_email() begins: reads the three required secrets out of the environment -- this is the "
             "only place credentials touch the script, and they only ever exist as process environment "
             "variables injected by the GitHub Actions workflow, never written to disk or logged."),
    (102, 106, "Builds a MIMEMultipart message with From/To headers and a Subject line that already "
               "summarizes the new/total counts, so they're visible in an inbox without opening the "
               "email."),
    (107, 114, "Composes the plain-text email body: the new/total counts again, both URLs, and a note that "
               "the full detail is in the attached PDF."),
    (115, 115, "Attaches that text body to the message."),
    (116, 116, "Blank line."),
    (117, 120, "Re-opens the PDF just written, wraps its bytes as a MIMEApplication attachment tagged with "
               "the right filename, and attaches it to the message."),
    (121, 121, "Blank line."),
    (122, 124, "Opens an SSL connection straight to Gmail's SMTP server on port 465, logs in with the app "
               "password, and sends the finished message to the recipient."),
    (125, 126, "Blank lines before main()."),
    (127, 130, "main() begins: loads every currently-tracked job and the saved report state, pulling out "
               "last_reported_utc."),
    (131, 131, "Blank line."),
    (132, 132, "Computes new_jobs as every job whose first_seen_utc string sorts after last_reported_utc -- "
               "this string comparison works correctly because both are ISO-8601 UTC timestamps, which "
               "sort lexicographically in the same order they occur chronologically."),
    (133, 133, "Captures the current time as the report's generated-at display string."),
    (134, 134, "Blank line."),
    (135, 136, "Builds the PDF, then immediately emails it along with the new/total counts."),
    (137, 137, "Blank line."),
    (138, 139, "Updates last_reported_utc in the state dict to now, and saves it -- the workflow commits "
               "this change afterward, so the next run's new_jobs comparison only picks up what's genuinely "
               "new since this email went out."),
    (140, 140, "Blank line."),
    (141, 141, "Prints a machine-readable RESULT summary line for the workflow log."),
    (142, 143, "Blank lines before the entry-point guard."),
    (144, 145, "Standard `if __name__ == \"__main__\": main()` guard."),
]

JOB_WATCH_YML_ANNOTATIONS = [
    (1, 1, "The workflow's display name, as it appears in the repo's Actions tab."),
    (2, 2, "Blank line."),
    (3, 6, "Triggers: a cron schedule (\"13 */5 * * *\" -- at minute 13 of every 5th hour, so roughly every "
           "5 hours around the clock) and workflow_dispatch, which adds the manual \"Run workflow\" button "
           "in the Actions tab."),
    (7, 7, "Blank line."),
    (8, 9, "Grants the workflow's default GITHUB_TOKEN write access to repository contents -- required "
           "because the last step below commits and pushes."),
    (10, 10, "Blank line."),
    (11, 13, "Defines a single job named \"scrape\", running on GitHub's standard ubuntu-latest runner "
             "image."),
    (14, 14, "Start of the step list."),
    (15, 15, "Checks out the repository so later steps can read and write its files."),
    (16, 16, "Blank line."),
    (17, 19, "Installs Python 3.12 on the runner via the official setup-python action."),
    (20, 20, "Blank line."),
    (21, 22, "Installs the scraper's two runtime dependencies directly (beautifulsoup4 for HTML parsing, "
             "selenium for browser automation); Chrome itself and a matching driver are supplied by the "
             "runner image together with Selenium's own driver-manager, so no separate browser-install "
             "step is needed."),
    (23, 23, "Blank line."),
    (24, 25, "Runs scrape.py -- this is the step that does the actual fetch/parse/dedupe/write work."),
    (26, 26, "Blank line."),
    (27, 37, "Commit-and-push step: configures a bot git identity, then only stages, commits, and pushes "
             "jobs.json/jobs.md/index.html if `git diff --quiet` reports they actually changed -- avoiding "
             "an empty commit on runs where nothing new was found -- and otherwise just logs that nothing "
             "changed."),
]

EMAIL_REPORT_YML_ANNOTATIONS = [
    (1, 1, "The workflow's display name -- distinct from the job-watch workflow so both show up clearly "
           "in the Actions tab."),
    (2, 2, "Blank line."),
    (3, 6, "Triggers: a cron schedule (\"0 3 */5 * *\" -- 03:00 UTC on days 1, 6, 11, 16, 21, 26 and 31 of "
           "each month) that approximates \"every 5 days\" -- standard cron can't express a true rolling "
           "interval across month boundaries, so this occasionally fires a day or two early at a month "
           "end -- plus workflow_dispatch for a manual run."),
    (7, 7, "Blank line."),
    (8, 9, "Grants write access to repository contents, needed to commit the updated report_state.json."),
    (10, 10, "Blank line."),
    (11, 13, "Defines a single job named \"report\", on ubuntu-latest."),
    (14, 14, "Start of the step list."),
    (15, 15, "Checks out the repository."),
    (16, 16, "Blank line."),
    (17, 19, "Installs Python 3.12."),
    (20, 20, "Blank line."),
    (21, 22, "Installs every dependency listed in requirements.txt -- this workflow only actually needs "
             "fpdf2, but reusing one shared requirements file keeps the two workflows simple and "
             "consistent."),
    (23, 23, "Blank line."),
    (24, 29, "Runs generate_report.py with the three secrets (SMTP_USER, SMTP_PASS, RECIPIENT_EMAIL) "
             "injected as environment variables for just this step -- this is the only place those "
             "credentials exist anywhere in the pipeline."),
    (30, 30, "Blank line."),
    (31, 41, "Commit step: configures a bot git identity, stages report_state.json, and only commits+pushes "
             "if it actually changed (mirrors the same guarded-commit pattern used in the job-watch "
             "workflow), so the timestamp used for next run's \"new since last report\" comparison is "
             "always the one that was really emailed."),
]

REQUIREMENTS_TXT_ANNOTATIONS = [
    (1, 1, "beautifulsoup4 -- HTML parsing library; scrape.py's parse_cards() uses it to pull structured "
           "fields out of each result card."),
    (2, 2, "fpdf2 -- PDF-generation library; used by generate_report.py to build the emailed summary, and "
           "by this document's own generator."),
    (3, 3, "selenium -- browser-automation library; scrape.py uses it to drive a real headless Chrome "
           "browser against LinkedIn's public guest search, instead of a raw HTTP request."),
]

FILES = [
    {
        "path": "scrape.py",
        "blurb": "The scraper. Runs every ~5 hours via GitHub Actions: drives headless Chrome against "
                 "LinkedIn's public, logged-out job-search endpoint, parses results, deduplicates them, "
                 "applies the 1-to-31-day freshness window, and writes jobs.json / jobs.md / index.html.",
        "annotations": SCRAPE_PY_ANNOTATIONS,
    },
    {
        "path": "generate_report.py",
        "blurb": "The email reporter. Runs roughly every 5 days: builds a PDF of new (or all) tracked "
                 "listings and emails it via Gmail SMTP, using credentials supplied only as GitHub Actions "
                 "secrets.",
        "annotations": GENERATE_REPORT_PY_ANNOTATIONS,
    },
    {
        "path": ".github/workflows/dsa-trainer-job-watch.yml",
        "blurb": "The GitHub Actions workflow that schedules and runs scrape.py, and commits its output "
                 "back to the repository when it changes.",
        "annotations": JOB_WATCH_YML_ANNOTATIONS,
    },
    {
        "path": ".github/workflows/email-report.yml",
        "blurb": "The GitHub Actions workflow that schedules and runs generate_report.py, supplying the "
                 "SMTP/recipient secrets and committing the updated report state.",
        "annotations": EMAIL_REPORT_YML_ANNOTATIONS,
    },
    {
        "path": "requirements.txt",
        "blurb": "The three third-party packages both scripts depend on.",
        "annotations": REQUIREMENTS_TXT_ANNOTATIONS,
    },
]

NOT_WALKED_THROUGH = [
    ("jobs.json", "Generated data -- the structured record of every currently-tracked listing. Rewritten "
                  "by scrape.py's write_outputs() on every run; not hand-authored."),
    ("jobs.md", "Generated data -- the same listings as a human-readable markdown table."),
    ("index.html", "Generated output -- the static live page served by GitHub Pages, rebuilt from "
                   "jobs_sorted by build_index_html() on every scrape.py run."),
    ("report_state.json", "Generated state -- just {\"last_reported_utc\": <timestamp>}, rewritten by "
                           "generate_report.py after every emailed report."),
    ("latest_report.pdf", "Generated output -- the most recent emailed PDF, rebuilt by generate_report.py "
                           "each time it runs."),
]


def add_title_page(pdf: FPDF):
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*HEADING_COLOR)
    pdf.ln(30)
    pdf.multi_cell(0, 12, safe("DSA Trainer Job Tracker"), align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 13)
    pdf.multi_cell(
        0, 8, safe("Code Walkthrough -- every authored line, explained"),
        align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*EXPLAIN_COLOR)
    pdf.multi_cell(
        0,
        6,
        safe(
            "Repository: github.com/yogesh889/DSA_Trainer_Online\n"
            "Live page: yogesh889.github.io/DSA_Trainer_Online\n\n"
            "This document walks through every file this project's automation actually runs -- "
            "scrape.py, generate_report.py, both GitHub Actions workflows, and requirements.txt -- "
            "one line (or one short block of blank/structural lines) at a time. Generated data files "
            "(jobs.json, jobs.md, index.html, report_state.json, latest_report.pdf) are produced by "
            "that code rather than hand-written, and are listed at the end instead of walked through "
            "line-by-line."
        ),
        align="L",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT,
    )
    pdf.set_text_color(*HEADING_COLOR)


def add_file_section(pdf: FPDF, path: str, blurb: str, annotations):
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(*HEADING_COLOR)
    pdf.cell(0, 10, safe(path), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*EXPLAIN_COLOR)
    pdf.multi_cell(0, 5.5, safe(blurb), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    full_path = REPO_DIR / path
    lines = full_path.read_text(encoding="utf-8").splitlines()

    for start, end, explanation in annotations:
        code_block = "\n".join(lines[start - 1:end])
        label = f"L{start}" if start == end else f"L{start}-{end}"

        pdf.set_font("Courier", "", 8.5)
        pdf.set_text_color(*HEADING_COLOR)
        pdf.set_fill_color(*CODE_FILL)
        pdf.multi_cell(
            0,
            4.2,
            safe(f"{label}:\n{code_block}" if code_block.strip() else f"{label}: (blank)"),
            fill=True,
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
        )

        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*EXPLAIN_COLOR)
        pdf.multi_cell(0, 5, safe(f"-> {explanation}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(2.5)


def add_closing_section(pdf: FPDF):
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 15)
    pdf.set_text_color(*HEADING_COLOR)
    pdf.cell(0, 10, safe("Generated files (not walked through line-by-line)"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    for name, note in NOT_WALKED_THROUGH:
        pdf.set_font("Courier", "B", 10)
        pdf.set_text_color(*HEADING_COLOR)
        pdf.cell(0, 6, safe(name), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(*EXPLAIN_COLOR)
        pdf.multi_cell(0, 5, safe(note), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(2)


def main():
    pdf = FPDF(orientation="L", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(left=14, top=14, right=14)

    add_title_page(pdf)
    for f in FILES:
        add_file_section(pdf, f["path"], f["blurb"], f["annotations"])
    add_closing_section(pdf)

    pdf.output(str(OUT_PATH))
    print(f"RESULT: wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
